#To install libraries please run this file on command prompt and write :"python3 install_libraries.py".
#PLEASE DO NOT EDIT THIS FILE
from os import system
print('please wait few second ...')
system('pip install -r libraries.txt')
print('Done')
